# Generated by Django 4.2 on 2023-05-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_cate', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='blogcategory',
            field=models.CharField(default='testing', max_length=200),
        ),
    ]
