# Generated by Django 4.2 on 2023-05-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_blogcategory_post_blogcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
