# Generated by Django 4.2 on 2023-06-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0005_alter_post_author_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
