# Generated by Django 4.2 on 2023-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_post_social_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='social_telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
