# Generated by Django 4.2 on 2023-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0007_post_social_facebook_post_social_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=200)),
            ],
        ),
    ]
